name: Benchmark PR
on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{github.workflow}} - ${{github.ref}}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Project
        uses: ./.github/actions/setup
        with:
          node-version: 24

      - name: Global Playwright Install
        run: npm install playwright -g

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Build
        run: npm run build:rollup

      - name: Run PR Benchmark and Compare
        uses: pixijs/performance-benchmark-action@main
        with:
          benchmark-path: './scripts/benchmarks'
          perf-change: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
