name: Benchmark Dev
on:
  push:
    branches: [dev]

concurrency:
  group: ${{github.workflow}} - ${{github.ref}}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Project
        uses: ./.github/actions/setup
        with:
          node-version: 24

      - name: Global Playwright Install
        run: npm install playwright -g

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Build
        run: npm run build:rollup

      - name: Run Dev Benchmark
        uses: pixijs/performance-benchmark-action@main
        with:
          dist-path: ./dist
          output-file: dev_result.json
          benchmark-path: './scripts/benchmarks'

      - uses: actions/upload-artifact@v4
        with:
          name: dev-benchmark
          path: dev_result.json
